### PR TITLE
I have added files via upload in templates folder under the name of index.html and global.css

### PR DESCRIPTION
**Pull request by Igdtuwresource**

### CODE REVIEW

**Comment by shawshankkumar** [comment]
Please add a description of what you've done.

**Comment by Igdtuwresource** [comment]
I have added html page and css page for user doesn't exist.
There is little animation in the text.
I have added these files in the template folder.
As, use hovers on user not found, it will get tilted little bit.

**Comment by Igdtuwresource** [comment]
@shawshankkumar merge it please

**Comment by meltedhyperion** [comment]
1) Add a screenshot of the HTML render.

2) The task was to render a 'user not found' page instead of just the message from the API.
You can check RsvpForEvent() in user-controller.go for this.

**Pull request closed without merging**
